name: 'Run swift-format'
description: 'Run swift-format'
branding:
  icon: 'truck'
  color: 'blue'
inputs:
  arguments:
    description: 'swift-format command arguments'
    required: true
  outputfile:
    description: 'output destination files'
    required: false
runs:
  using: 'docker'
  image: 'docker://tokorom/swift-format:5.6'
  env:
    SWIFT_FORMAT_ARGUMENTS: ${{ inputs.arguments }}
    SWIFT_FORMAT_OUTPUTFILE: ${{ inputs.outputfile }}
