name: 'Run swift-format'
description: 'Run swift-format'
branding:
  icon: 'truck'
  color: 'blue'
inputs:
  arguments:
    description: 'swift-format command arguments'
    required: true
runs:
  using: 'docker'
  image: 'docker://tokorom/swift-format:latest'
  env:
    SWIFT_FORMAT_ARGUMENTS: ${{ inputs.arguments }}
  args:
    - ''
