name: Danger
on:
  push:
    branches:
      - sample

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: tokorom/swift-format-github-action@sample
      with:
        arguments: 'format --recursive --in-place .'
    - run: 'git status | grep modified:'
    - name: Create Pull Request
      if: ${{ success() }}
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'Automatically formatted by swift-format'
        base: sample
        branch: swift-format/patch
        branch-suffix: timestamp
        delete-branch: true
        title: 'Automatically formatted by swift-format'
        body: 'To merge into this branch, you need to follow the rules of swift-format.'
