name: swift-format
on:
  push:
    branches:
      - sample

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: tokorom/swift-format-github-action@sample
      with:
        arguments: 'format --recursive --in-place .'
    - uses: tokorom/swift-format-github-action@sample
      with:
        arguments: 'lint --recursive . &>problems.txt'
    - run: 'cat problems.txt'
