name: Danger
on:
  push:
    branches:
      - sample

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - runs:
      using: 'docker'
      image: 'docker://tokorom/swift-format:latest'
      entrypoint: ["swift-format", "lint", "--recurcive", "."]
